<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\MoviesRental.Domain\MoviesRental.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UseCases\Dvds\Commands\CreateDvd\" />
    <Folder Include="UseCases\Dvds\Commands\DeleteDvd\" />
    <Folder Include="UseCases\Dvds\Commands\ReturnDvd\" />
    <Folder Include="UseCases\Dvds\Commands\RentDvd\" />
    <Folder Include="UseCases\Dvds\Commands\UpdateDvd\" />
  </ItemGroup>

</Project>
